# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.modifications_batch import ModificationsBatch

class TestModificationsBatch(unittest.TestCase):
    """ModificationsBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModificationsBatch:
        """Test ModificationsBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModificationsBatch`
        """
        model = ModificationsBatch()
        if include_optional:
            return ModificationsBatch(
                modifications = [
                    null
                    ],
                modifier_id = 56,
                modifier_type = 'agent'
            )
        else:
            return ModificationsBatch(
                modifications = [
                    null
                    ],
                modifier_type = 'agent',
        )
        """

    def testModificationsBatch(self):
        """Test ModificationsBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
