# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.user_update_password_request import UserUpdatePasswordRequest

class TestUserUpdatePasswordRequest(unittest.TestCase):
    """UserUpdatePasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdatePasswordRequest:
        """Test UserUpdatePasswordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdatePasswordRequest`
        """
        model = UserUpdatePasswordRequest()
        if include_optional:
            return UserUpdatePasswordRequest(
                password = ''
            )
        else:
            return UserUpdatePasswordRequest(
                password = '',
        )
        """

    def testUserUpdatePasswordRequest(self):
        """Test UserUpdatePasswordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
