# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.api.demo_api import DemoApi


class TestDemoApi(unittest.TestCase):
    """DemoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DemoApi()

    def tearDown(self) -> None:
        pass

    def test_get_demo_demo_request_uuid_get(self) -> None:
        """Test case for get_demo_demo_request_uuid_get

        Get Demo
        """
        pass

    def test_list_demo_demo_list_get(self) -> None:
        """Test case for list_demo_demo_list_get

        List Demo
        """
        pass

    def test_request_demo_demo_request_post(self) -> None:
        """Test case for request_demo_demo_request_post

        Request Demo
        """
        pass


if __name__ == '__main__':
    unittest.main()
