# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.agent_run_status import AgentRunStatus

class TestAgentRunStatus(unittest.TestCase):
    """AgentRunStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentRunStatus(self):
        """Test AgentRunStatus"""
        # inst = AgentRunStatus()

if __name__ == '__main__':
    unittest.main()
