# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.modifications_batch_modifications_inner import ModificationsBatchModificationsInner

class TestModificationsBatchModificationsInner(unittest.TestCase):
    """ModificationsBatchModificationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModificationsBatchModificationsInner:
        """Test ModificationsBatchModificationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModificationsBatchModificationsInner`
        """
        model = ModificationsBatchModificationsInner()
        if include_optional:
            return ModificationsBatchModificationsInner(
                name = '',
                role_description = '',
                node_id = 56,
                plan_id = '',
                params = {
                    'key' : null
                    },
                adapter_query = occam_sdk.models.adapter_query.AdapterQuery(
                    query_string = '', 
                    name = '', ),
                type = None,
                data_source_access_name = '',
                is_proposed = True,
                src_type = 'ToolPlanNode',
                src = 56,
                target = 56,
                src_output_field = '',
                target_input_field = ''
            )
        else:
            return ModificationsBatchModificationsInner(
                name = '',
                role_description = '',
                node_id = 56,
                plan_id = '',
                src_type = 'ToolPlanNode',
                src = 56,
                target = 56,
                src_output_field = '',
                target_input_field = '',
        )
        """

    def testModificationsBatchModificationsInner(self):
        """Test ModificationsBatchModificationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
