# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.update_user_active_announcement_request import UpdateUserActiveAnnouncementRequest

class TestUpdateUserActiveAnnouncementRequest(unittest.TestCase):
    """UpdateUserActiveAnnouncementRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserActiveAnnouncementRequest:
        """Test UpdateUserActiveAnnouncementRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserActiveAnnouncementRequest`
        """
        model = UpdateUserActiveAnnouncementRequest()
        if include_optional:
            return UpdateUserActiveAnnouncementRequest(
                free_credits_announcement_active = True,
                auto_recharge_failed_announcement_active = True
            )
        else:
            return UpdateUserActiveAnnouncementRequest(
        )
        """

    def testUpdateUserActiveAnnouncementRequest(self):
        """Test UpdateUserActiveAnnouncementRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
