# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.agent_role import AgentRole

class TestAgentRole(unittest.TestCase):
    """AgentRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentRole(self):
        """Test AgentRole"""
        # inst = AgentRole()

if __name__ == '__main__':
    unittest.main()
