# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.api.key_api import KeyApi


class TestKeyApi(unittest.TestCase):
    """KeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeyApi()

    def tearDown(self) -> None:
        pass

    def test_create_key_keys_put(self) -> None:
        """Test case for create_key_keys_put

        Create Key
        """
        pass

    def test_delete_key_keys_uuid_delete(self) -> None:
        """Test case for delete_key_keys_uuid_delete

        Delete Key
        """
        pass

    def test_get_key_usage_keys_uuid_usage_get(self) -> None:
        """Test case for get_key_usage_keys_uuid_usage_get

        Get Key Usage
        """
        pass

    def test_list_keys_keys_get(self) -> None:
        """Test case for list_keys_keys_get

        List Keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
