# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent_agents_agent_name_create_post(self) -> None:
        """Test case for create_agent_agents_agent_name_create_post

        Create Agent
        """
        pass

    def test_get_agent_agents_agent_name_get(self) -> None:
        """Test case for get_agent_agents_agent_name_get

        Get Agent
        """
        pass

    def test_get_agent_run_status_agents_agent_run_instance_id_status_get(self) -> None:
        """Test case for get_agent_run_status_agents_agent_run_instance_id_status_get

        Get Agent Run Status
        """
        pass

    def test_list_agents_agents_get(self) -> None:
        """Test case for list_agents_agents_get

        List Agents
        """
        pass

    def test_run_agent_agents_agent_instance_id_run_post(self) -> None:
        """Test case for run_agent_agents_agent_instance_id_run_post

        Run Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
