# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from occam_sdk.models.plan_modifier_type import PlanModifierType

class TestPlanModifierType(unittest.TestCase):
    """PlanModifierType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanModifierType(self):
        """Test PlanModifierType"""
        # inst = PlanModifierType()

if __name__ == '__main__':
    unittest.main()
