# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from occam_sdk.models.adapter_query import AdapterQuery
from typing import Optional, Set
from typing_extensions import Self

class EditNode(BaseModel):
    """
    EditNode
    """ # noqa: E501
    plan_id: StrictStr
    node_id: StrictInt
    params: Optional[Dict[str, Any]] = None
    adapter_query: Optional[AdapterQuery] = None
    type: Optional[Any] = None
    __properties: ClassVar[List[str]] = ["plan_id", "node_id", "params", "adapter_query", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EditNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of adapter_query
        if self.adapter_query:
            _dict['adapter_query'] = self.adapter_query.to_dict()
        # set to None if adapter_query (nullable) is None
        # and model_fields_set contains the field
        if self.adapter_query is None and "adapter_query" in self.model_fields_set:
            _dict['adapter_query'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EditNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plan_id": obj.get("plan_id"),
            "node_id": obj.get("node_id"),
            "params": obj.get("params"),
            "adapter_query": AdapterQuery.from_dict(obj["adapter_query"]) if obj.get("adapter_query") is not None else None,
            "type": obj.get("type")
        })
        return _obj
