# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from occam_sdk.models.get_resource_response import GetResourceResponse
from typing import Optional, Set
from typing_extensions import Self

class GetResourcesResponse(BaseModel):
    """
    GetResourcesResponse
    """ # noqa: E501
    connected: List[GetResourceResponse]
    unconnected: List[GetResourceResponse]
    __properties: ClassVar[List[str]] = ["connected", "unconnected"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetResourcesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in connected (list)
        _items = []
        if self.connected:
            for _item_connected in self.connected:
                if _item_connected:
                    _items.append(_item_connected.to_dict())
            _dict['connected'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in unconnected (list)
        _items = []
        if self.unconnected:
            for _item_unconnected in self.unconnected:
                if _item_unconnected:
                    _items.append(_item_unconnected.to_dict())
            _dict['unconnected'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetResourcesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connected": [GetResourceResponse.from_dict(_item) for _item in obj["connected"]] if obj.get("connected") is not None else None,
            "unconnected": [GetResourceResponse.from_dict(_item) for _item in obj["unconnected"]] if obj.get("unconnected") is not None else None
        })
        return _obj
