# coding: utf-8

"""
    Occam AI's public API

    API exposing Occam AI's planning, execution and supervision capabilities.

    The version of the OpenAPI document: 6.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RunMetrics(BaseModel):
    """
    RunMetrics
    """ # noqa: E501
    duration_minutes: Optional[Union[StrictFloat, StrictInt]]
    cost_dollars: Optional[Union[StrictFloat, StrictInt]]
    success_rate: Optional[Union[StrictFloat, StrictInt]]
    metrics_are_estimates: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["duration_minutes", "cost_dollars", "success_rate", "metrics_are_estimates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RunMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.duration_minutes is None and "duration_minutes" in self.model_fields_set:
            _dict['duration_minutes'] = None

        # set to None if cost_dollars (nullable) is None
        # and model_fields_set contains the field
        if self.cost_dollars is None and "cost_dollars" in self.model_fields_set:
            _dict['cost_dollars'] = None

        # set to None if success_rate (nullable) is None
        # and model_fields_set contains the field
        if self.success_rate is None and "success_rate" in self.model_fields_set:
            _dict['success_rate'] = None

        # set to None if metrics_are_estimates (nullable) is None
        # and model_fields_set contains the field
        if self.metrics_are_estimates is None and "metrics_are_estimates" in self.model_fields_set:
            _dict['metrics_are_estimates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RunMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "duration_minutes": obj.get("duration_minutes"),
            "cost_dollars": obj.get("cost_dollars"),
            "success_rate": obj.get("success_rate"),
            "metrics_are_estimates": obj.get("metrics_are_estimates")
        })
        return _obj
